### ISSUE TITLE
Issue with buttons without icons

### ISSUE THREAD

**Issue by AlainMelsens** [burlingtonbytes/wp-blockade#3]
Hello,
When I put buttons without icons (options No Icon), just like on the home page on your example on www.wpblockade.com, in the Tinymce editor, everything seems to be fine.
But after publishing the page, on the screen, it seems that there is a space before the button label. 
The label seems not to be in the center of the button. It seems that there is a hidden icon on the button at the left from the button label. See also the screendumps in attachments.
Please, can someone help me to find the reason for this behavior on the screen?
Thanks in advance.
Best Regards,
Alain Melsens
![2017-06-15 11_28_40-buttons in tinymce editor](https://user-images.githubusercontent.com/25772012/27175249-de45d85a-51be-11e7-8f77-22bcaa000e8c.jpg)
![2017-06-15 11_28_40-buttons after publishing](https://user-images.githubusercontent.com/25772012/27175255-e25b295e-51be-11e7-8f8f-c3970c8c2c16.jpg)

**Comment by AlainMelsens** [comment]
Hello,
I found myself a working solution, but maybe it's not the best place to modify some programming options?
Anyway, in the WordPress folder structure: wp-content\plugins\wp-blockade\addons\button there is a plugin.js Javascript file where buttons were made.
In the "apply_form_results : function( data, form_data, block )" function, I have changed the if-then test instruction to: if( form_data.icon && form_data.icon.length > 1)
Because the "no icon" selection does not give an empty form_data.icon variable. So, I added simply the lenght value more than 1 and then it's working fine as you can see on the attached screendump.
![solution buttons after publishing](https://user-images.githubusercontent.com/25772012/27341636-223a6d46-55de-11e7-9950-3b73741873ee.jpg)
Please, may I ask to verify these solution and if it's fine then, please take it in the next upgrade or modify it following your internal programming rules.
Thanks in advance.
Best Regards,
Alain Melsens

**Comment by gschoppe** [comment]
You've correctly identified the defect, and your fix should work for now. Ideally I'll need to identify why the empty selection is returning a value that isn't falsy, to fix this properly, or it will just pop up in other fields.  The file change you have in place will get overwritten by the next update, but I'll make sure similar logic is in place in that version to solve the issue, so it won't cause incompatibilities.

**Comment by AlainMelsens** [comment]
Hello,
Thanks for your answer. I'm not a fulltime programmer, so, I don't have enough experience to verify other incompatibilities. They are your sources. So, maybe it should beter that you and your colleques will check this more in details.
Otherwise I was glad to help you. I really need this brand new idea to give WordPress content also a more visually and graphically layout. 
Thank you very much to take this fix in the next update. I will close this ticket now.
Best Regards,
Alain Melsens
