### ISSUE TITLE
How to activate wp-blockade on tinymce editor in other text widgets?

### ISSUE THREAD

**Issue by AlainMelsens** [burlingtonbytes/wp-blockade#4]
Hello,
Should it be possible to activate wp-blockade on tinymce editor in other text widgets?
I use also the free Live Composer plugin to build pages. In Live Composer there is a text widget where you can use the tinymce editor but at this point there is no wp-blockade active to use it.
The wp-blockade plugin is already activated and I can use it only at page level, but not in text widgets.
Is there any way to have wp-blockade also active in text widgets?
Thanks in advance.
Best Regards.

**Comment by gschoppe** [comment]
In general it is possible to add Blockade anywhere that tinyMCE is instantiated with a call to `the_editor()`. It's certainly not officially supported functionality, and while Blockade won't actively break use cases like this, there is nothing stopping Live Composer from modifying their code in such a way that it breaks the integration.

All that said, I did some digging in Live Composer's source code, and figured out the snippet you'd need to activate blockade in their "WordPress Editor" view:

```
<?php
add_filter('wp-blockade-override-editors', function($editors) {
	$editors[] = 'dslcawpeditor';
	return $editors;
});
```

**Comment by AlainMelsens** [comment]
Perfect! It's just what I need! :)
Thank you very much for your fast reply and also for the correct code that I have placed in the functions.php of my current used theme.
Thanks again.

**Comment by AlainMelsens** [comment]
Hello,
I have tried to put your code into a WordPress plugin in place of the functions.php file from my used theme, but it doesn't work. I get no errors but the WP Blockade will not be active anymore in LC text editors. 
Must I change the code when I want it in a plugin, or is it simply not possible to activate WP Blockade in other LC text widgets via a Wordpress plugin?
Thanks in advance.

**Comment by gschoppe** [comment]
hmmm,
I don't see any reason why it shouldn't work in a plugin. I was testing it in an mu-plugin when I wrote it.  are you sure the plugin is active and the code is being called?

**Comment by AlainMelsens** [comment]
Sure, the plugin is active but it's not working as before. Maybe there is some little code to add before or at the end of a plugin to properly calling de code? I'm not a real PHP or Wordpress programmer. Or maybe some other parameters in the functions or so...?
But it's strange that it doesn't give errors. Only it doesn't work.
Thanks in advance for any help.

**Comment by gschoppe** [comment]
If you email me the plugin file, I'd be happy to take a look for you... one of the annoying parts of WordPress is that if you get the filter name or name of the callable function wrong in an add_filter call, it fails silently.

**Comment by AlainMelsens** [comment]
Ok, thanks, I have just sended you an email to your GMail emailaddress.
Thanks in advance to look at it.

**Comment by gschoppe** [comment]
ok, I think I see the issue... you have a check in your plugin, to see whether live composer is installed or not... however, when you run your code in a plugin, it may run before the live composer plugin is initiated. If that happens, the check returns false, and the code inside isn't run.

There are three ways to solve the issue.

**Option 1:** In this specific case, there is no need to check if Live Composer is installed before running the filter, as it just adds the name of the live composer editor to the list of editors that blockade targets. If that editor doesn't exist, it doesn't effect the operation of Blockade, so removing that check would solve the problem.

If it was necessary, you could do one of two things:

**Option 2:** There is a 'plugins_loaded' action that fires immediately after all plugins are loaded. That hook could contain the other code.  It would look like this (using anonymous functions for brevity):

```
add_action('plugins_loaded', function() {
  if ( defined( 'DS_LIVE_COMPOSER_URL' ) ) {
    add_filter('wp-blockade-override-editors', function($editors) {
      $editors[] = 'dslcawpeditor';
      return $editors;
    });
  }
});
```

**Option 3:** Because the blockade filter in question runs after plugin initialization, the check for live composer could be moved into that filter.

``` 	
add_filter('wp-blockade-override-editors', function($editors) {
  if ( defined( 'DS_LIVE_COMPOSER_URL' ) ) {
    $editors[] = 'dslcawpeditor';
  }
  return $editors;
});
```

**Comment by AlainMelsens** [comment]
All right! Thank you very much for this great explanation. Indeed, this way, it works as expected.
Only a very little detail, in your code explained in Option 3, the very latest bracket "}" is not needed.
Again, thank you so much for your kindness to help me with this issue. 
Both super tools WP Blockade and Live Composer gives me the power and possibilities that I really needed.
Best Regards and keep going the good work! ;)

**Comment by gschoppe** [comment]
You're correct... I just updated the comment to address that.  Glad everything is working for you!

**Comment by AlainMelsens** [comment]
Hello,
I saw that there is an other issue.
When I use wp-blockade in the visual mode in the tinyMCE in a text widget from Live Composer, I can't paste simple text that I have copied before elsewhere. When I try the same case but outside Live Composer, that is working whithout problems. I have tried with the mouse click from the Edit menu but also with the shortcut keys from my keyboard (Ctrl + V) and nothing is working. I don't recieve error messages either. There is nothing pasted.
Is there a solution for it, please?
Thanks in advance.
