### ISSUE TITLE
Pasting text in text widget with wp-blockade in Live Composer not working

### ISSUE THREAD

**Issue by AlainMelsens** [burlingtonbytes/wp-blockade#5]
Hello,
I saw that there is an other issue.
When I use wp-blockade in the visual mode in the tinyMCE in a text widget from Live Composer, I can't paste simple text that I have copied before elsewhere. When I try the same case but outside Live Composer, that is working whithout problems. I have tried with the mouse click from the Edit menu but also with the shortcut keys from my keyboard (Ctrl + V) and nothing is working. I don't recieve error messages either. There is nothing pasted.
Is there a solution for it, please?
Thanks in advance.

**Comment by gschoppe** [comment]
I just pushed a new version that should fix the issue. But if you can verify the fix, that would help us out. I believe your issue is the same as one we saw with carbonfields in our internal testing but hadn't isolated yet. That issue is now fixed, and hopefully should also apply to Live Composer.

**Comment by AlainMelsens** [comment]
Hello,
I have tested it and it is indeed better, but I can only paste text with the shortkey Ctrl + V and I must click twice before the pasted text is placed.
So, I don't know if you have tried also to fix the other methode to paste with the Edit menu because this is not working yet.

**Comment by gschoppe** [comment]
Ok, I am still hunting down and patching related paste issues, and I want to make sure I have them solved before I release another version, but I think your issue can be solved by removing line 319 from the file `core-plugins/blockade/plugin.js`

The line to remove is: `var mce = document.getElementById('content_ifr').contentWindow.document.getElementById('tinymce'); `

If you have the ability to test this, I'd love to verify that it works for you.  Once I have another small paste bug solved, I will release a 0.9.10 with this fix.

**Comment by AlainMelsens** [comment]
Hello,
I have test it and when I put the cursor where I want that the pasted text must appear, when I use the shortuct Ctrl + V, the placed text is pasted from the clipboard memory at the beginning of the content area of the tinyMCE editor as show here below:
![image](https://user-images.githubusercontent.com/25772012/33474555-7f32c9da-d67b-11e7-890d-ac4eaa2af811.png)
When I try a second time, then the text is placed at the right place where the cursor is placed.
![image](https://user-images.githubusercontent.com/25772012/33474677-eef4ad1a-d67b-11e7-8b79-44811e78c215.png)
So, it is better, but in fact, there are 2 actions needed and also the first pasted text must be delete it because it's the wrong place. This is not the normal way as usual when paste text. It should be pasted at the wright place where the cursor stays at the first time.
Otherwise, I don't know if your fixes are working also when using the Edit menu from the tinyMCE editor?  
![image](https://user-images.githubusercontent.com/25772012/33474183-c45d2958-d679-11e7-8f28-af573d79c7c5.png)
Because this is not working when clicking on the menu item "Paste" and also not when clicking "Paste as text". There is nothing that will be pasted this way.

**Comment by gschoppe** [comment]
The misplaced paste content is part of the related issue I mentioned that is delaying me from pushing a 0.9.10 release. I am not yet certain why that is occurring, but I should have an answer soon.

As for the TinyMCE paste menu, that isn't a default WordPress feature.. are you using a plugin to restore TinyMCE features that WordPress strips? if so, which one? I can't guarantee that I'll be able to get perfect compatibility with these additional features, but I can look into it, and see what I can do.

**Comment by AlainMelsens** [comment]
Ok, I appriciate your efforts to look at this issues.
Yes, I use the "TinyMCE Advanced" plugin by Andrew Ozz. You're right, this plugin let's set other menus active in the TinyMCE editor.
But even with the "TinyMCE Advanced" plugin deactivated, there is an icon wich can be used to "Paste as text" and this seems also not to work either.
![image](https://user-images.githubusercontent.com/25772012/33488223-50ee7a26-d6b0-11e7-8231-ee9cc2bab937.png)

**Comment by gschoppe** [comment]
Sorry for the delay, this one took me an incredibly long time to diagnose, but actually seems to be an issue with TinyMCE in modern browsers, such as Chrome. For security reasons, Chrome doesn't allow JavaScript to read the clipboard when a user clicks a button or menu item rendered by JavaScript, so the paste menu item simply doesn't work in these browsers.

Usually, when you click the paste menu item, TinyMCE will show an error message telling you to change browsers or paste using either the right-click menu or ctrl-v... however, Live Composer renders the editor above the error message, so it cannot be seen.

In my testing, the issue occurs whether Blockade is enabled or not.

as for the toolbar button you mention in your last screenshot, that isn't actually a paste button. It toggles the paste mode for ctrl+v between "paste" and "paste text only" modes. In my testing that appears to be working properly.

It appears the only remaining paste issue is the one that causes some paste contents to appear at the top of the editor, rather than where intended.

**Comment by AlainMelsens** [comment]
Hello,
Ok, I understand. I will look at your suggestions and see how they work.
Thank you very much for your time and diagnose.

**Comment by AlainMelsens** [comment]
Hello,
I have tested and for me it's sufficiant. Pasting texts are working well as expected.
Thank you very much to help resolving very quickly such issues. This is good for the productivity of your plugin. I really appreciate it.
Keep going the good work. :)
This ticket may be closed.
