### ISSUE TITLE
How to activate wp-blockade on tinymce editor in "Elementor" text widgets

### ISSUE THREAD

**Issue by AlainMelsens** [burlingtonbytes/wp-blockade#6]
Hello,
Should it be posiible to activate wp-blockade plugin in the free "Elementor" pagebuilder?
I think that this is almost the same methode as you have done previously with the text widgets in Live Composer.
I tought I could do it myself with the PHP code as following:
`<?php
add_filter('wp-blockade-override-editors', function($editors) {
	$editors[] = 'editor';
	return $editors;
});`
But it doesn't seems to work. Maybe it's the $editors[] = 'editor'; that is wrong?
Could you look for it, please?
And why I have moved from Live Composer to Elementor?
Because Elementor works faster and the GUI is especially also more user/developer friendly. It gives more productivity. I need to construct my own theme with custom Header and custom Footer.
Thanks in advance for your help.

**Comment by gschoppe** [comment]
This is definitely outside the normal of supported uses for Blockade, and may not work as expected (Elementor has modified many of their TinyMCE settings, and may not even be loaded by the common WordPress hooks). I won't be able to help with detailed debugging for this, if it causes issue.

That said, it looks like Elementor uses the ID 'elementorwpeditor' when loading the TinyMCE settings, so this snippet might work (emphasis on *might*):
`<?php add_filter('wp-blockade-override-editors', function($editors) { $editors[] = 'elementorwpeditor'; return $editors; });`

**Comment by AlainMelsens** [comment]
Thanks for your quick response.
And, at first sight, yes, it's working, but I will test it a little bit more before I start screaming glory. :)
If you know what I mean...
I will certainly keep you informed as soon as possible.
Again, thank you very much for your amazing help. I appreciate it.
